### PR TITLE
Update iml unit testing docs

### PR DESCRIPTION
**Pull request by johnsonw**
The unit testing docs are outdated. Update these docs to reflect how
testing works in travis and use a docker container to run tests locally.

Signed-off-by: Will Johnson <wjohnson@whamcloud.com>

### CODE REVIEW

**Comment by jgrund** [comment]
What are you seeing running within a volume?

**Comment by johnsonw** [comment]
```
python -W always manage.py test tests/unit/
Loaded 13 default power device types.
Creating groups...
***
***
***
*** SECURITY WARNING: You are running in DEBUG mode and default users have been created
***
***
***

E
======================================================================
ERROR: Failure: ImportError (No module named iml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 79, in importFromDir
    fh, filename, desc = find_module(part, path)
ImportError: No module named iml

----------------------------------------------------------------------
Ran 1 test in 0.001s

```

**Comment by johnsonw** [comment]
copying the files over and running the same command in the copied directory seems to resolve the issue.

**Comment by jgrund** [comment]
What's the `iml` it's trying to import?

**Comment by johnsonw** [comment]
Here's what I have so far:

```
> /usr/local/lib/python2.7/dist-packages/nose/importer.py(81)importFromDir()
-> fh, filename, desc = find_module(part, path)
(Pdb) l
 76  	                acquire_lock()
 77  	                log.debug("find module part %s (%s) in %s",
 78  	                          part, part_fqname, path)
 79  	                from remote_pdb import RemotePdb
 80  	                RemotePdb("127.0.0.1", 4444).set_trace()
 81  ->	                fh, filename, desc = find_module(part, path)
 82  	                old = sys.modules.get(part_fqname)
 83  	                if old is not None:
 84  	                    # test modules frequently have name overlap; make sure
 85  	                    # we get a fresh copy of anything we are trying to load
 86  	                    # from a new path
(Pdb) part
'iml'
(Pdb) path
['/iml']
(Pdb) find_module('iml', '/iml')
*** ImportError: No frozen submodule named /iml.iml
```

**Pull request merged**
